### ISSUE TITLE
page.exit type is wrong

### ISSUE THREAD

**Issue by ramiel** [typed-typings/visionmedia-page.js#1]
The type for the function `page.exit` is

```ts
  function exit(path: string, callback: Callback, moreCallbacks?: Callback[]): void;
```

but it should be

```ts
  function exit(path: string, callback: Callback, ...moreCallbacks: Callback[]): void;
```

**Comment by unional** [comment]
Thanks. Feel free to open a PR 🌷

**Comment by ramiel** [comment]
Yes, I tried actually, as you can see I forked the repo but I'm not able to run the build and the tests, so I'm not sure how to proceed. I hope you can fix this

**Comment by unional** [comment]
Got it. I take a look at it and the tool chain is pretty outdated.
 
Have made the change without tests.
